properties:
  hours-before-close: 3
server:
  servlet:
    context-path: /backend/
  port: ${PORT:8080}
spring:
  application:
    name: ${RETAILER_NAME:Food4Good}
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:1MB}
      max-request-size: ${MAX_FILE_SIZE:1MB}
  datasource:
    url: jdbc:postgresql://${PG_HOST:127.0.0.1}:${PG_PORT:5432}/${PG_DATABASE:test}?prepareThreshold=0
    username: ${PG_USER:postgres}
    password: ${PG_PASS:12345678}
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-database-schemas: true
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        hbm2dll:
          extra_physical_table_types: "MATERIALIZED VIEW"
          create_namespaces: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
logging:
  level:
    org.hibernate:
      SQL: ${LOG_LEVEL_DB:debug}
      type:
        descriptor:
          sql: ${LOG_LEVEL_DB:debug}
  register-shutdown-hook: true